
/**************************************************************/
/*                                                            */
/*               Copyright (c) Siemens 2021                   */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF SIEMENS       */
/*             CORPORATION OR ITS LICENSORS AND IS            */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for conv_2d.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 5.1.0
//* Generated on: May. 24, 2022 12:54:06 PM, (user: russk)
//*>


#pragma once

#include "conv_2d_model.h"

#include "ac_int.h"
#include "ac_float.h"


using namespace tlm;

//This class inherits from the conv_2d_pv_base class

class conv_2d_pv : public conv_2d_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(conv_2d_pv);
  conv_2d_pv(sc_core::sc_module_name module_name);  
  
 protected:
  /////////////////////////////////////////
  // write callbacks of registers
  ////////////////////////////////////////// 
  void cb_write_go(unsigned int newValue);  

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size); 
  virtual void cb_transport_dbg_go(tlm::tlm_generic_payload& trans); 
  bool slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   

public:
  typedef ac_fixed<32,16,true> hw_cat_type;

private:
  unsigned int vista_read_bus(unsigned int x);
  void vista_write_bus(unsigned int a, unsigned int d);
  void conv_2d_vista();
  int in_bounds(int r, int c, int height, int width);
  int offset(int row, int col, int image, int height, int width, int images);
  int weight_offset(int row, int col, int input_image, int output_image, int height, int width, int num_input_images, int num_output_images);
  void set_cat_value(int m, unsigned int address, hw_cat_type data);
  hw_cat_type get_cat_value(int m, unsigned int address);
  void print_image(int image_offset, int height, int width);
  void print_filter(int filter_offset, int height, int width);


};

