
/**************************************************************/
/*                                                            */
/*               Copyright (c) Siemens 2021                   */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF SIEMENS       */
/*             CORPORATION OR ITS LICENSORS AND IS            */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for conv_2d.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 5.1.0
//* Generated on: May. 24, 2022 12:54:06 PM, (user: russk)
//*>


#include "conv_2d_t.h"

#ifdef __conv_2d_t_base_CLASS_EXIST__
#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;



conv_2d_t_base* conv_2d_t_base::create_t(const char* name, long simulation) {
  return new conv_2d_t(name, simulation);
}


conv_2d_t::conv_2d_t(sc_module_name _name, long simulation)
  : conv_2d_t_base(_name, simulation) {
  
}


#endif
